/**
 * API error contract (§89). Every error response from the API MUST match this
 * shape. The frontend switches on `error.code`, never on `error.message`
 * (message is for logs/debugging, may change wording without notice).
 */
export interface ApiErrorBody {
  error: {
    code: ApiErrorCode;
    message: string;
    /** Optional field-level validation details (DTO validation failures). */
    details?: Record<string, string[]>;
  };
}

export const ApiErrorCode = {
  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INVALID_OR_EXPIRED_TOKEN: "INVALID_OR_EXPIRED_TOKEN",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  INVALID_GOOGLE_TOKEN: "INVALID_GOOGLE_TOKEN",
  SOCIAL_LOGIN_DISABLED: "SOCIAL_LOGIN_DISABLED",

  // Events
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_CAPACITY_REACHED: "EVENT_CAPACITY_REACHED",
  REGISTRATION_CLOSED: "REGISTRATION_CLOSED",
  ALREADY_REGISTERED: "ALREADY_REGISTERED",
  EVENT_REQUIRES_MODERATION: "EVENT_REQUIRES_MODERATION",
  EVENT_NOT_PUBLISHABLE: "EVENT_NOT_PUBLISHABLE",
  EVENT_ALREADY_CANCELLED: "EVENT_ALREADY_CANCELLED",
  MEDIA_LIMIT_REACHED: "MEDIA_LIMIT_REACHED",

  // Credits / payments
  INSUFFICIENT_LISTING_CREDITS: "INSUFFICIENT_LISTING_CREDITS",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  FREE_CREDITS_ALREADY_CLAIMED: "FREE_CREDITS_ALREADY_CLAIMED",

  // Social
  FRIEND_REQUEST_ALREADY_EXISTS: "FRIEND_REQUEST_ALREADY_EXISTS",
  USER_BLOCKED: "USER_BLOCKED",

  // Reviews
  REVIEW_NOT_ELIGIBLE: "REVIEW_NOT_ELIGIBLE",
  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",

  // Media
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
} as const;
export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
